"""Added BlogTable

Revision ID: 5ae2009e3b1a
Revises: a750fc3ca03c
Create Date: 2020-04-13 01:17:59.080623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ae2009e3b1a'
down_revision = 'a750fc3ca03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('blog', mysql.LONGTEXT(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_table')
    # ### end Alembic commands ###
