"""Initial migration.

Revision ID: a750fc3ca03c
Revises: 
Create Date: 2020-04-12 22:41:11.319484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a750fc3ca03c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ascii_table',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('art', mysql.LONGTEXT(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ascii_table')
    # ### end Alembic commands ###
